# Generated by Django 6.0 on 2026-01-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
        migrations.AddField(
            model_name='profile',
            name='nick',
            field=models.CharField(default='user', max_length=64),
            preserve_default=False,
        ),
    ]
