# Generated by Django 6.0 on 2026-01-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_profile_nickname_profile_nick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nick',
            field=models.CharField(max_length=64),
        ),
    ]
