worker_processes 1;
events { worker_connections 1024; }

http {
  include mime.types; default_type application/octet-stream; sendfile on;
  gzip on; gzip_min_length 1024;
  gzip_types text/plain text/css application/javascript application/json image/svg+xml;

  proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=ASKCACHE:10m max_size=200m inactive=10m;
  upstream django_upstream { server 127.0.0.1:8000; }

  server {
    listen 80; server_name localhost;

    location ^~ /uploads/ { alias /home/pylounge/projects/ask_pupkin; expires 30d; add_header Cache-Control "public"; }
    location ~* \.[^/]+$ { root /home/pylounge/projects/ask_pupkin; expires 30d; add_header Cache-Control "public"; }

    location / {
      proxy_pass http://django_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_cache ASKCACHE;
      proxy_cache_valid 200 10m;
      add_header X-Cache-Status $upstream_cache_status;
    }
  }
}
